# Generated by Django 4.2.7 on 2023-11-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_rename_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
